INSERT INTO system_config (`id`, `k`, `remark`) VALUES (1, 'siteName', '站点名称');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (5, 'storageStrategy', '当前启用存储引擎');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (6, 'username', '管理员账号');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (7, 'password', '管理员密码');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (8, 'domain', '站点域名');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (11, 'customCss', '自定义 CSS');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (12, 'customJs', '自定义 JS (可用于统计代码)');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (13, 'tableSize', '表格大小');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (14, 'showOperator', '是否显示操作按钮');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (15, 'showDocument', '是否显示文档');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (16, 'announcement', '网站公告');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (17, 'showAnnouncement', '是否显示网站公告');
INSERT INTO system_config (`id`, `k`, `remark`) VALUES (18, 'layout', '页面布局');